# Generated by Django 5.1.5 on 2025-04-10 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_mobileclinicrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileclinicrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 10, 17, 42, 29, 77117)),
            preserve_default=False,
        ),
    ]
