# Generated by Django 5.1.5 on 2025-04-10 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mobileclinicrequest_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRAccessControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_access', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
                ('patient', models.OneToOneField(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='treatment_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_visible_to_other_hospitals', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('document', models.FileField(upload_to='treatment_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(limit_choices_to={'user_type': 'hospital'}, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'user_type': 'patient'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
