# Generated by Django 5.1.5 on 2025-04-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_qraccesscontrol_treatmentfile_treatmentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecord',
            name='is_visible_to_others',
            field=models.BooleanField(default=True),
        ),
    ]
