# Generated by Django 5.1.5 on 2025-04-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_treatmentrecord_is_visible_to_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qraccesscontrol',
            name='allow_access',
            field=models.BooleanField(default=True),
        ),
    ]
